version: '3.9'

services:
  nginx:
    build: .
    image: nginx-dev:v1
    container_name: nginx-dev
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - servicio-cuentas
      - servicio-usuarios
      - servicio-sensores

  frontend:
    build:
      context: ./frontend-microservicios
      dockerfile: Dockerfile.dev
    image: frontend-microservicios-dev:v1
    container_name: frontend-microservicios-dev
    volumes:
      - ./frontend-microservicios:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s

  servicio-usuarios:
    build:
      context: ./microservicio-usuarios
      dockerfile: Dockerfile.dev
    image: microservicio-usuarios-dev:v1
    container_name: microservicio-usuarios-dev
    volumes:
      - ./microservicio-usuarios:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql-usuarios:
        condition: service_healthy
    env_file:
      - ./microservicio-usuarios/.env
  
  servicio-cuentas:
    build:
      context: ./microservicio-cuentas
      dockerfile: Dockerfile.dev
    image: microservicio-cuentas-dev:v1
    container_name: microservicio-cuentas-dev
    volumes:
      - ./microservicio-cuentas:/app
      - /app/node_modules
    ports:
      - "3002:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql-cuentas:
        condition: service_healthy
    env_file:
      - ./microservicio-cuentas/.env

  servicio-sensores:
    build:
      context: ./microservicio-sensores
      dockerfile: Dockerfile.dev
    image: microservicio-sensores-dev:v1
    container_name: microservicio-sensores-dev
    volumes:
      - ./microservicio-sensores:/app
      - /app/node_modules
    ports:
      - "3003:3000"
    depends_on:
      mysql-sensores:
        condition: service_healthy
    env_file:
      - ./microservicio-sensores/.env
  
  mysql-usuarios:
    image: mysql:latest
    container_name: mysql-usuarios-dev
    ports:
      - "${DB_USUARIOS_DEV_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_USUARIOS_DEV_PASSWORD}
      - MYSQL_DATABASE=${DB_USUARIOS_DEV_DATABASE}
      - MYSQL_USER=${DB_USUARIOS_DEV_USERNAME}
      - MYSQL_PASSWORD=${DB_USUARIOS_DEV_PASSWORD}
    volumes:
      - mysql-usuarios-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
  
  mysql-cuentas:
    image: mysql:latest
    container_name: mysql-cuentas-dev
    ports:
      - "${DB_CUENTAS_DEV_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_CUENTAS_DEV_PASSWORD}
      - MYSQL_DATABASE=${DB_CUENTAS_DEV_DATABASE}
      - MYSQL_USER=${DB_CUENTAS_DEV_USERNAME}
      - MYSQL_PASSWORD=${DB_CUENTAS_DEV_PASSWORD}
    volumes:
      - mysql-cuentas-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s

  mysql-sensores:
    image: mysql:latest
    container_name: mysql-sensores-dev
    ports:
      - "${DB_SENSORES_DEV_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_SENSORES_DEV_PASSWORD}
      - MYSQL_DATABASE=${DB_SENSORES_DEV_DATABASE}
      - MYSQL_USER=${DB_SENSORES_DEV_USERNAME}
      - MYSQL_PASSWORD=${DB_SENSORES_DEV_PASSWORD}
    volumes:
      - mysql-sensores-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
   
volumes:
  mysql-usuarios-data:
  mysql-cuentas-data:
  mysql-sensores-data:
  rabbitmq-data: